services:
  db:
    image: postgres:16
    container_name: woow_db
    environment:
      POSTGRES_USER: woow
      POSTGRES_PASSWORD: woowpass
      POSTGRES_DB: woowdb
    ports:
      - "5433:5432"
    volumes:
      - woow_pgdata:/var/lib/postgresql/data

volumes:
  woow_pgdata: